version: '3.8'
services:
  nestjs:
    build: .
    volumes:
      - data:/home/server/
    ports:
      - 80:8080
  dev-db:
    image: postgres:13
    restart: always
    volumes: 
      - data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
      PGDATA : /var/lib/postgresql/data/pgdata
    networks:
      - poznanie-network
  test-db:
    image: postgres:13
    restart: always
    volumes: 
      - data:/var/lib/postgresql/test-data
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
      PGDATA : /var/lib/postgresql/test-data/pgdata
    networks:
      - poznanie-network
volumes:
  data:
networks:
  poznanie-network: